import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Link from "next/link";
import { auth } from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <SessionProvider>
        <body className={inter.className}>
          <div className="navbar bg-base-300 flex justify-center absolute">
            <div className="max-w-6xl w-full flex justify-between">
              <Link href="/" className="btn btn-ghost text-xl">
                Ai gym tracker
              </Link>
              {session && (
                <Link className="btn btn-primary" href="/api/auth/signout">
                  Sing out
                </Link>
              )}
            </div>
          </div>
          {children}
        </body>
      </SessionProvider>
    </html>
  );
}
